// <auto-generated />
using DataAnnotation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAnnotation.Migrations
{
    [DbContext(typeof(QLBanHangContext))]
    partial class QLBanHangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAnnotation.Models.HangHoa", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("DonGia")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHang");

                    b.HasIndex("MaLoai");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("DataAnnotation.Models.LoaiHang", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiHang");
                });

            modelBuilder.Entity("DataAnnotation.Models.HangHoa", b =>
                {
                    b.HasOne("DataAnnotation.Models.LoaiHang", "LoaiHang")
                        .WithMany("HangHoa")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHang");
                });

            modelBuilder.Entity("DataAnnotation.Models.LoaiHang", b =>
                {
                    b.Navigation("HangHoa");
                });
#pragma warning restore 612, 618
        }
    }
}
