// <auto-generated />
using HocDBFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HocDBFirst.Migrations
{
    [DbContext(typeof(QlnhanSuContext))]
    [Migration("20250605013311_InitSchoolDB")]
    partial class InitSchoolDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HocDBFirst.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A876F1AB0");

                    b.HasIndex("MaPhong");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("HocDBFirst.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaPhong")
                        .HasName("PK__PhongBan__20BD5E5B8B05B2B2");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("HocDBFirst.Models.NhanVien", b =>
                {
                    b.HasOne("HocDBFirst.Models.PhongBan", "MaPhongNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK__NhanVien__MaPhon__398D8EEE");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("HocDBFirst.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
